### ISSUE TITLE
Running tox fails

### ISSUE THREAD

**Issue by lowks** [lowks/minimock#1]
Running tox fails with the following error: 

```
Failure: ImportError (No module named docs) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named docs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lowks/Projects/src/Python/minimock/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/Users/lowks/Projects/src/Python/minimock/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
ImportError: No module named docs

----------------------------------------------------------------------
Ran 1 test in 0.001s
```
This is due to the missing ```docs``` directory. Is this line needed or some plans for it ?

**Comment by jab** [comment]
not sure where that was coming from (couldn't reproduce), but as of #3, tox is running in the travis build successfully as well as for me locally. is it not working for you?

**Comment by lowks** [comment]
I commented one line out from test to make it work



[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by jab** [comment]
See https://github.com/lowks/minimock/pull/3#issuecomment-183895605
